#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ] || [ -n "${HASHED_PASSWORD}" ]; then
    AUTH="password"
else
    AUTH="none"
    echo "starting with no password"
fi

if [ -z ${PROXY_DOMAIN+x} ]; then
    PROXY_DOMAIN_ARG=""
else
    PROXY_DOMAIN_ARG="--proxy-domain=${PROXY_DOMAIN}"
fi

exec \
    s6-setuidgid ${USER_NAME} \
        /app/code-server/bin/code-server \
            --bind-addr 0.0.0.0:${PORT} \
            --user-data-dir ${USER_HOME_DIR}/data \
            --extensions-dir ${USER_HOME_DIR}/extensions \
            --disable-telemetry \
            --auth "${AUTH}" \
            "${PROXY_DOMAIN_ARG}" \
            "${DEFAULT_WORKSPACE:-${USER_HOME_DIR}/workspace}"
