#!/bin/bash

_sed_remove_empty_line() {
	# remove all empty line, need '' after -i on macos, can use ^$ to catch the empty line
	# and ^\s*$ for emtpy line with space (\s*)
	sed -i "" "/^\s*$/d" "${1}"
}
_sed_remove_comment_line() {
	# remove all comment lines, line start with space or tab too
	# ex:
	# # comment text
	#     # comment text
	#			# comment text
	sed -i "" "/^[[:blank:]]*#/d" "${1}"
}
_sed_remove_all_occur() {
	# delete all matching ${1}
	sed -i "" "/${1}/d" "${2}"
}
_sed_replace_first_occur() {
	# replace ${1} with ${2} - sed '1,/string/ s/string/replacement/' file
	sed -i "" "1,/${1}/ s/${1}/${2}/" ${3}
}
_sed_replace_all_occur() {
	sed -i "" "s/${1}/${2}/g" ${3}
}
